wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1500
enable_wandb:
  desc: null
  value: true
save_model:
  desc: null
  value: true
check_frequency:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694540142.999626
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.10
      8:
      - 3
      - 5
